//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public RsMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsMenu", typeof(RsMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string lbAccion {
            get {
                return ResourceManager.GetString("lbAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string lbBorrar {
            get {
                return ResourceManager.GetString("lbBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea borrar la siguiente información?.
        /// </summary>
        public static string lbBorrarEntidad {
            get {
                return ResourceManager.GetString("lbBorrarEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string lbCancelar {
            get {
                return ResourceManager.GetString("lbCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string lbCerrar {
            get {
                return ResourceManager.GetString("lbCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string lbEntrar {
            get {
                return ResourceManager.GetString("lbEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error autenticación.
        /// </summary>
        public static string lbErrorAutenticacion {
            get {
                return ResourceManager.GetString("lbErrorAutenticacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error guardando en base de datos.
        /// </summary>
        public static string lbErrorBaseDeDatos {
            get {
                return ResourceManager.GetString("lbErrorBaseDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error comunicación.
        /// </summary>
        public static string lbErrorComunicacion {
            get {
                return ResourceManager.GetString("lbErrorComunicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, valide, hace falta información o no está en los límites.
        /// </summary>
        public static string lbFaltaInformacion {
            get {
                return ResourceManager.GetString("lbFaltaInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string lbGuardar {
            get {
                return ResourceManager.GetString("lbGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string lbLimpiar {
            get {
                return ResourceManager.GetString("lbLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, Llame al administrador.
        /// </summary>
        public static string lbLlameAlAdmin {
            get {
                return ResourceManager.GetString("lbLlameAlAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguno de los datos tiene mal formato.
        /// </summary>
        public static string lbMalFormato {
            get {
                return ResourceManager.GetString("lbMalFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string lbMensaje {
            get {
                return ResourceManager.GetString("lbMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string lbModicar {
            get {
                return ResourceManager.GetString("lbModicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        public static string lbNotas {
            get {
                return ResourceManager.GetString("lbNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string lbNuevo {
            get {
                return ResourceManager.GetString("lbNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        public static string lbPersonas {
            get {
                return ResourceManager.GetString("lbPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrescar.
        /// </summary>
        public static string lbRefrescar {
            get {
                return ResourceManager.GetString("lbRefrescar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir.
        /// </summary>
        public static string lbSeleccionar {
            get {
                return ResourceManager.GetString("lbSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, valide, los datos ingresados.
        /// </summary>
        public static string lbValideDatos {
            get {
                return ResourceManager.GetString("lbValideDatos", resourceCulture);
            }
        }
    }
}
