//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsPersonas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public RsPersonas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsPersonas", typeof(RsPersonas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVO.
        /// </summary>
        public static string clActivo {
            get {
                return ResourceManager.GetString("clActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEDULA.
        /// </summary>
        public static string clCedula {
            get {
                return ResourceManager.GetString("clCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDAD.
        /// </summary>
        public static string clEdad {
            get {
                return ResourceManager.GetString("clEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string clId {
            get {
                return ResourceManager.GetString("clId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMBRE.
        /// </summary>
        public static string clNombre {
            get {
                return ResourceManager.GetString("clNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test5
        ///.
        /// </summary>
        public static string lbActivo {
            get {
                return ResourceManager.GetString("lbActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test3.
        /// </summary>
        public static string lbCedula {
            get {
                return ResourceManager.GetString("lbCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test4
        ///.
        /// </summary>
        public static string lbEdad {
            get {
                return ResourceManager.GetString("lbEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test2.
        /// </summary>
        public static string lbPersona {
            get {
                return ResourceManager.GetString("lbPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test1.
        /// </summary>
        public static string lbSingular {
            get {
                return ResourceManager.GetString("lbSingular", resourceCulture);
            }
        }
    }
}
